# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Af < Formula
  desc "altFINS CLI for market data, analytics, signals, and TUI workflows"
  homepage "https://altfins.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/altfins-com/altfins-cli/releases/download/v0.3.0/af_0.3.0_darwin_amd64.tar.gz"
      sha256 "3b140a1e841a65f64cc00299b8be707a6c39d38754335d05f8045260dbe01751"

      define_method(:install) do
        bin.install "af"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/altfins-com/altfins-cli/releases/download/v0.3.0/af_0.3.0_darwin_arm64.tar.gz"
      sha256 "530fc6a277bdd0aded1266f6fa2ce67590dad2f88cff4b4b39507e12cf7ce26d"

      define_method(:install) do
        bin.install "af"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/altfins-com/altfins-cli/releases/download/v0.3.0/af_0.3.0_linux_amd64.tar.gz"
      sha256 "30588ec51abe183ecf4268e5ad4805c367d1ed81f6b32493180bdecd0f48fe7a"
      define_method(:install) do
        bin.install "af"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/altfins-com/altfins-cli/releases/download/v0.3.0/af_0.3.0_linux_arm64.tar.gz"
      sha256 "36480a4c8e1ac2d3127618683a0a6210e6ebbd921ef60470247d2b4596958358"
      define_method(:install) do
        bin.install "af"
      end
    end
  end
end
